project:
  type: website
  output-dir: .

website:
  title: "Rebecca Luttinen"
  site-url: https://rebeccaluttinen.github.io/

format:
  html:
    theme: cosmo
    minimal: false  

resources:
  - images/
