project:
  type: website

website:
  title: "Rebecca Luttinen"
  site-url: https://rluttinen.github.io/RebeccaLuttinen.github.io/
  site-path: "/RebeccaLuttinen.github.io/"

format:
  html:
    theme: cosmo
    minimal: false  

resources:
  - images/
